// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: patrol.proto

package patrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PatrolID string `protobuf:"bytes,2,opt,name=PatrolID,proto3" json:"PatrolID,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	Host     string `protobuf:"bytes,4,opt,name=Host,proto3" json:"Host,omitempty"`
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Attachment) GetPatrolID() string {
	if x != nil {
		return x.PatrolID
	}
	return ""
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// 巡河
type Patrol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	ID         int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID     int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PatrolID   string                 `protobuf:"bytes,3,opt,name=PatrolID,proto3" json:"PatrolID,omitempty"`
	Line       string                 `protobuf:"bytes,4,opt,name=Line,proto3" json:"Line,omitempty"`
	CreateAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	Attachment []*Attachment          `protobuf:"bytes,7,rep,name=Attachment,proto3" json:"Attachment,omitempty"`
	Memo       string                 `protobuf:"bytes,8,opt,name=Memo,proto3" json:"Memo,omitempty"`
}

func (x *Patrol) Reset() {
	*x = Patrol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patrol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patrol) ProtoMessage() {}

func (x *Patrol) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patrol.ProtoReflect.Descriptor instead.
func (*Patrol) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{1}
}

func (x *Patrol) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Patrol) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Patrol) GetPatrolID() string {
	if x != nil {
		return x.PatrolID
	}
	return ""
}

func (x *Patrol) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Patrol) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *Patrol) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *Patrol) GetAttachment() []*Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *Patrol) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type GetPatrolByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID int64 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *GetPatrolByIDRequest) Reset() {
	*x = GetPatrolByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatrolByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolByIDRequest) ProtoMessage() {}

func (x *GetPatrolByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPatrolByIDRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatrolByIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetPatrolByIDRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetPatrolByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patrol *Patrol `protobuf:"bytes,1,opt,name=Patrol,proto3" json:"Patrol,omitempty"`
}

func (x *GetPatrolByIDResponse) Reset() {
	*x = GetPatrolByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatrolByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolByIDResponse) ProtoMessage() {}

func (x *GetPatrolByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolByIDResponse.ProtoReflect.Descriptor instead.
func (*GetPatrolByIDResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{3}
}

func (x *GetPatrolByIDResponse) GetPatrol() *Patrol {
	if x != nil {
		return x.Patrol
	}
	return nil
}

type GetPatrolListByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Page     int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *GetPatrolListByUserIDRequest) Reset() {
	*x = GetPatrolListByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatrolListByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolListByUserIDRequest) ProtoMessage() {}

func (x *GetPatrolListByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolListByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetPatrolListByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatrolListByUserIDRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetPatrolListByUserIDRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPatrolListByUserIDRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPatrolListByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patrol []*Patrol `protobuf:"bytes,1,rep,name=Patrol,proto3" json:"Patrol,omitempty"`
	Count  int64     `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *GetPatrolListByUserIDResponse) Reset() {
	*x = GetPatrolListByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatrolListByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolListByUserIDResponse) ProtoMessage() {}

func (x *GetPatrolListByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolListByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetPatrolListByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatrolListByUserIDResponse) GetPatrol() []*Patrol {
	if x != nil {
		return x.Patrol
	}
	return nil
}

func (x *GetPatrolListByUserIDResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

//
type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patrol *Patrol `protobuf:"bytes,1,opt,name=Patrol,proto3" json:"Patrol,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{6}
}

func (x *PostRequest) GetPatrol() *Patrol {
	if x != nil {
		return x.Patrol
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patrol *Patrol `protobuf:"bytes,1,opt,name=Patrol,proto3" json:"Patrol,omitempty"`
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{7}
}

func (x *PostResponse) GetPatrol() *Patrol {
	if x != nil {
		return x.Patrol
	}
	return nil
}

type DelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{8}
}

func (x *DelRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{9}
}

func (x *DelResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patrol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_patrol_proto protoreflect.FileDescriptor

var file_patrol_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x22,
	0x91, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4d, 0x65, 0x6d, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d,
	0x65, 0x6d, 0x6f, 0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06,
	0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50,
	0x61, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x66, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x56, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72,
	0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x52,
	0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2e, 0x0a,
	0x0b, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06,
	0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50,
	0x61, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x2f, 0x0a,
	0x0c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x1c,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x1d, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x1f, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x20, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x32, 0x9f,
	0x02, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x0a,
	0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x0c, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x50, 0x61,
	0x74, 0x72, 0x6f, 0x6c, 0x12, 0x0b, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x12,
	0x0e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_patrol_proto_rawDescOnce sync.Once
	file_patrol_proto_rawDescData = file_patrol_proto_rawDesc
)

func file_patrol_proto_rawDescGZIP() []byte {
	file_patrol_proto_rawDescOnce.Do(func() {
		file_patrol_proto_rawDescData = protoimpl.X.CompressGZIP(file_patrol_proto_rawDescData)
	})
	return file_patrol_proto_rawDescData
}

var file_patrol_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_patrol_proto_goTypes = []interface{}{
	(*Attachment)(nil),                    // 0: Attachment
	(*Patrol)(nil),                        // 1: Patrol
	(*GetPatrolByIDRequest)(nil),          // 2: GetPatrolByIDRequest
	(*GetPatrolByIDResponse)(nil),         // 3: GetPatrolByIDResponse
	(*GetPatrolListByUserIDRequest)(nil),  // 4: GetPatrolListByUserIDRequest
	(*GetPatrolListByUserIDResponse)(nil), // 5: GetPatrolListByUserIDResponse
	(*PostRequest)(nil),                   // 6: PostRequest
	(*PostResponse)(nil),                  // 7: PostResponse
	(*DelRequest)(nil),                    // 8: DelRequest
	(*DelResponse)(nil),                   // 9: DelResponse
	(*UpdateRequest)(nil),                 // 10: UpdateRequest
	(*UpdateResponse)(nil),                // 11: UpdateResponse
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
}
var file_patrol_proto_depIdxs = []int32{
	12, // 0: Patrol.CreateAt:type_name -> google.protobuf.Timestamp
	12, // 1: Patrol.UpdateAt:type_name -> google.protobuf.Timestamp
	0,  // 2: Patrol.Attachment:type_name -> Attachment
	1,  // 3: GetPatrolByIDResponse.Patrol:type_name -> Patrol
	1,  // 4: GetPatrolListByUserIDResponse.Patrol:type_name -> Patrol
	1,  // 5: PostRequest.Patrol:type_name -> Patrol
	1,  // 6: PostResponse.Patrol:type_name -> Patrol
	2,  // 7: PatrolService.GetPatrol:input_type -> GetPatrolByIDRequest
	4,  // 8: PatrolService.GetPatrolList:input_type -> GetPatrolListByUserIDRequest
	6,  // 9: PatrolService.PostPatrol:input_type -> PostRequest
	8,  // 10: PatrolService.DelPatrol:input_type -> DelRequest
	10, // 11: PatrolService.UpdatePatrol:input_type -> UpdateRequest
	3,  // 12: PatrolService.GetPatrol:output_type -> GetPatrolByIDResponse
	5,  // 13: PatrolService.GetPatrolList:output_type -> GetPatrolListByUserIDResponse
	7,  // 14: PatrolService.PostPatrol:output_type -> PostResponse
	9,  // 15: PatrolService.DelPatrol:output_type -> DelResponse
	11, // 16: PatrolService.UpdatePatrol:output_type -> UpdateResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_patrol_proto_init() }
func file_patrol_proto_init() {
	if File_patrol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_patrol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patrol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatrolByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatrolByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatrolListByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatrolListByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patrol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_patrol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patrol_proto_goTypes,
		DependencyIndexes: file_patrol_proto_depIdxs,
		MessageInfos:      file_patrol_proto_msgTypes,
	}.Build()
	File_patrol_proto = out.File
	file_patrol_proto_rawDesc = nil
	file_patrol_proto_goTypes = nil
	file_patrol_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PatrolServiceClient is the client API for PatrolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PatrolServiceClient interface {
	//
	GetPatrol(ctx context.Context, in *GetPatrolByIDRequest, opts ...grpc.CallOption) (*GetPatrolByIDResponse, error)
	GetPatrolList(ctx context.Context, in *GetPatrolListByUserIDRequest, opts ...grpc.CallOption) (*GetPatrolListByUserIDResponse, error)
	PostPatrol(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	DelPatrol(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	UpdatePatrol(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type patrolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatrolServiceClient(cc grpc.ClientConnInterface) PatrolServiceClient {
	return &patrolServiceClient{cc}
}

func (c *patrolServiceClient) GetPatrol(ctx context.Context, in *GetPatrolByIDRequest, opts ...grpc.CallOption) (*GetPatrolByIDResponse, error) {
	out := new(GetPatrolByIDResponse)
	err := c.cc.Invoke(ctx, "/PatrolService/GetPatrol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) GetPatrolList(ctx context.Context, in *GetPatrolListByUserIDRequest, opts ...grpc.CallOption) (*GetPatrolListByUserIDResponse, error) {
	out := new(GetPatrolListByUserIDResponse)
	err := c.cc.Invoke(ctx, "/PatrolService/GetPatrolList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) PostPatrol(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/PatrolService/PostPatrol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) DelPatrol(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, "/PatrolService/DelPatrol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) UpdatePatrol(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/PatrolService/UpdatePatrol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatrolServiceServer is the server API for PatrolService service.
type PatrolServiceServer interface {
	//
	GetPatrol(context.Context, *GetPatrolByIDRequest) (*GetPatrolByIDResponse, error)
	GetPatrolList(context.Context, *GetPatrolListByUserIDRequest) (*GetPatrolListByUserIDResponse, error)
	PostPatrol(context.Context, *PostRequest) (*PostResponse, error)
	DelPatrol(context.Context, *DelRequest) (*DelResponse, error)
	UpdatePatrol(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedPatrolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPatrolServiceServer struct {
}

func (*UnimplementedPatrolServiceServer) GetPatrol(context.Context, *GetPatrolByIDRequest) (*GetPatrolByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatrol not implemented")
}
func (*UnimplementedPatrolServiceServer) GetPatrolList(context.Context, *GetPatrolListByUserIDRequest) (*GetPatrolListByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatrolList not implemented")
}
func (*UnimplementedPatrolServiceServer) PostPatrol(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPatrol not implemented")
}
func (*UnimplementedPatrolServiceServer) DelPatrol(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelPatrol not implemented")
}
func (*UnimplementedPatrolServiceServer) UpdatePatrol(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePatrol not implemented")
}

func RegisterPatrolServiceServer(s *grpc.Server, srv PatrolServiceServer) {
	s.RegisterService(&_PatrolService_serviceDesc, srv)
}

func _PatrolService_GetPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatrolByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).GetPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PatrolService/GetPatrol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).GetPatrol(ctx, req.(*GetPatrolByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_GetPatrolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatrolListByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).GetPatrolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PatrolService/GetPatrolList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).GetPatrolList(ctx, req.(*GetPatrolListByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_PostPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).PostPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PatrolService/PostPatrol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).PostPatrol(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_DelPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).DelPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PatrolService/DelPatrol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).DelPatrol(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_UpdatePatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).UpdatePatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PatrolService/UpdatePatrol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).UpdatePatrol(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PatrolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PatrolService",
	HandlerType: (*PatrolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPatrol",
			Handler:    _PatrolService_GetPatrol_Handler,
		},
		{
			MethodName: "GetPatrolList",
			Handler:    _PatrolService_GetPatrolList_Handler,
		},
		{
			MethodName: "PostPatrol",
			Handler:    _PatrolService_PostPatrol_Handler,
		},
		{
			MethodName: "DelPatrol",
			Handler:    _PatrolService_DelPatrol_Handler,
		},
		{
			MethodName: "UpdatePatrol",
			Handler:    _PatrolService_UpdatePatrol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patrol.proto",
}
